### ISSUE TITLE
Credo.Check.Readability.LargeNumbers formatting (feature request)

### ISSUE THREAD

**Issue by edennis** [adobe/elixir-styler#109]
## Versions

* Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Styler: 0.11.1

## Example Input

```elixir
149_00
```

## Stacktrace / Current Behaviour
```elixir
14_900
```

First off, thanks for this awesome library! So far we've really been enjoying how it speeds up the feedback loop in dev cycles. 💪🏻 

## Context
We're working in a very large ecommerce code base that deals with pricing in cents and we've been using the underscore to delimit large prices at the cents/dollars barrier, i.e. $149.00 would be written as `149_00` in our tests. The default formatting for styler is to rewrite this as `14_900` which isn't ideal for our use case. Would you be open for a PR that would change the behavior for large numbers to only apply the default delimiting for numbers that aren't already delimited?

## Suggested Change
```
Number  Rewrite
1000    1000    # don't touch numbers smaller than 10000 (current implementation)
10000   10_000  # format numbers >= 10000 that are not already delimited (current implementation)
100_00  100_00  # don't touch numbers >= 10000 that are already delimited (new behavior)
```

**Comment by novaugust** [comment]
hey erick thanks for the compliments, nice writeup, & suggestion! you have a really valid use case here and i completely understand your pain. but it seems so particular to the ecommerce domain that im not sure that i want to incorporate it into styler.

the discarding of existing `_` is an intentional fix for human errors splitting a big number up at the "right" spot (it fixed a few cases of that in our own codebase). but i get that in your codebase, what i'm calling "errors" are intentional and well reasoned!  but i'm hesitant to remove what's a feature in our codebase to accommodate another, even though i do agree that what you're doing is very rational and understandable -- it's just very specific to that situation.

i'll let this sit for a little and dwell on it, but right now i feel it's unlikely that i make that change. apologies in advance ❤️

**Comment by novaugust** [comment]
ah well, [greg came in with the same idea](https://github.com/adobe/elixir-styler/pull/110#issuecomment-1858026655) this morning. i think he's spot on re: keeping a fork. thanks again for the thoughtful issue

**Comment by GregMefford** [comment]
You may also want to check out [the `money` library](https://github.com/elixirmoney/money), which is helpful for this kind of thing. Or [the `Decimal` library](https://hexdocs.pm/decimal/readme.html) if you don't want to go that far.
