### ISSUE TITLE
[Feature Request] Close up newlines between single-line function heads

### ISSUE THREAD

**Issue by peake100** [adobe/elixir-styler#13]
## Elixir / OTP Version

```shell
❯ elixir --version
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 25)
```

## Current Behaviour

When styler collapses functions to a single line, it does not bring the heads together. Something like this:

```elixir
some_func(arg) when is_integer(arg), do: arg

some_func(arg) when is_binary(arg),
    do: arg

some_func(arg), do: arg
```

... gets styled as this:

```elixir
some_func(arg) when is_integer(arg), do: arg

some_func(arg) when is_binary(arg), do: arg

some_func(arg), do: arg
```

## Expected Behaviour

The function heads should be closed up together:

```elixir
some_func(arg) when is_integer(arg), do: arg
some_func(arg) when is_binary(arg), do: arg
some_func(arg), do: arg
```

**Comment by novaugust** [comment]
should be very doable - i had the same thought recently =)

feel free to open a PR - i think it'll be as simple as deleting `newlines` from the meta of any keyworded def (see `Defs` style, there'll be a comment about where it's handling the `, do:` syntax)  - thought it might instead be deleting newlines from their body, which'll be a little messier

otherwise i'll tackle it at some point in the future

**Comment by novaugust** [comment]
spiked against this in #17 ^, but it looks like the only way to get a good implementation of your proposal is to rewrite Defs to mimic the layout of ModuleDirectives. So, it'll be awhile before I'm able to do that =)

**Comment by novaugust** [comment]
sorry billy, don't think this one's ever going to happen :X was looking at my own many-one-liner def recently and had it split out in weird ways i liked 😂 don't reckon i'll update styler to make that sad. thx for the suggestion though ❤️
