### ISSUE TITLE
[Feature Request] Configuration File

### ISSUE THREAD

**Issue by MDodge0811** [adobe/elixir-styler#26]
It would be awesome if this project had a config file that allowed choosing which formatting rules are applied, and potentially which directories they're applied to. 

This project would be invaluable for allowing us to implement some credo rules that we're currently unable to due to the time a full refactor would take. Due to the size of our codebase though, we would need to run the refactoring in smaller, testable chunks.

**Comment by novaugust** [comment]
>This project would be invaluable for allowing us to implement some credo rules that we're currently unable to due to the time a full refactor would take. Due to the size of our codebase though, we would need to run the refactoring in smaller, testable chunks.

You can always run `mix format` with only specified files, rather than letting your formatter config dictate it for you

```ex
mix format lib/direct_we_want_to_turn_credo_on_in
```
if the issue is that you just want to run the credo stuff and don't like our defs, you can delete [styles from here](https://github.com/adobe/elixir-styler/blob/main/lib/styler.ex#L20-L25) to just get what you want =)

**Comment by novaugust** [comment]
released 0.6.0 with `mix style` restored to ease styling a codebase. hopefully that gets you what you wanted =) 
we don't have adding configuration anywhere on the roadmap for now.

**Comment by novaugust** [comment]
hope `mix style` helped, cheers
