### ISSUE TITLE
Question about Styler.Style.SingleNode

### ISSUE THREAD

**Issue by epinault** [adobe/elixir-styler#89]
What is the difference between Styler.Style.SingleNode and Styler.Style.Blocks? They seem per the doc to achieve the same things?

**Comment by novaugust** [comment]
There's absolutely no real difference between any of the Style modules, they're just how I organize the code to help me reason about things and keep myself focused :) For those two, `SingleNode` is ideally just small and easy 1-liner replacements with no line manipulation - which means it doesn't need to think about comments.

Blocks is focused on anything with a `do` block in them (that isn't a defX anyways). Code gets moved around a lot in those block manipulations, and so it's more likely to need comments to be manipulated as well.

Happy to continue the discussion, just closing this since it's not an issue =)
